### ISSUE TITLE
Bug that prevents me from playing any further

### ISSUE THREAD

**Issue by ghost** [yosh778/YsVIII-tools#3] opened 2017-09-27 11:16 UTC
The bug happens on the first campfire scene with Hummel, more specifically, when he begins stating the rules of a "transporter". The game freezes on that moment and only the [Select] button works inside the game. This has happened twice.

Savefile: 
The save starts at the camp before Beast Hills, the one on the cave near the beach. Everything else is done so you simply need to go to Beast Hills, trigger the encounter scene, then go north until the campfire event.

[PCSG00881.zip](https://github.com/yosh778/YsVIII-tools/files/1336824/PCSG00881.zip)

**Comment by jayzt** [comment] 2017-09-27 18:13
This also happened to me. I'll try to go back to this scene and try skipping it if the game continues. Will update later.

**Comment by xYuunaX** [comment] 2017-09-27 20:08
seems skipping the cutscene works. (Confirmed by VanKaji)
Until this is fixed, for now just watch the cutscene and reload save to skip it.

**Comment by ghost** [comment] 2017-09-27 21:22
A detail on cutscene skipping: if it's done mid-action (like the group just walking) the game freezes for around 15~ seconds. If it's done at the end of a dialogue (for example, when it gives you the option to advance), the skipping is instant.

**Comment by xYuunaX** [comment] 2017-09-28 04:16
Found the culprit file rootast/script/mp4102t2.bin, replacing this with the jp version works. Investigating on how to fix.

**Comment by yosh778** [comment] 2017-09-28 06:49
Nice looks like an animation, at least it's not encrypted so could be fixable

**Comment by jayzt** [comment] 2017-10-01 04:48
found another freeze bug just before dr. kirkeegard battle. will try to replace the file mentioned and try it again if it freezes. 

edit: I dont think replacing the file mentioned fixes the problem since its a different script. Please let me know what script has the problem and I'll create a new rootast.xai

**Comment by yosh778** [comment] 2017-10-01 08:55
Ok yeah otherwise I'd advise to just watch buggy scenes online (not sure full japanese / chinese scenes are any use, though at least it wouldn't crash indeed)

**Comment by xYuunaX** [comment] 2017-10-02 15:31
@jayzt since you know the details and circumstances of your game progress. I would advise that you use notepad++ and open all the .bin files in the /script folder, and do a 'search in all documents' , search the key words that are only present in that specific cut-scene. If you don't mind, please report back which file is the culprit.

Also an update on fixes to the .bin files, unfortunately due to the complexity of these files, we haven't been very successful.

I did fix the animation sequence, but for some reason the cutscene does not transition to the next, and skipping doesn't work either.. (Probably due to me trying to fix it via hex editing)


Thanks!

UPDATE: mp1103.bin is the culprit on the next crash, @ Dr. kiergaard (Can be skipped)

**Comment by xYuunaX** [comment] 2017-10-06 10:10
Update: Both cutscenes have been fixed, will be released with next or final version. Please keep reporting on bugged cutscenes. 

Thanks!

**Closed as completed** 2017-10-08 14:36 UTC
Labels: bug

**Comment by zuzuzuririri** [comment] 2018-07-11 17:47
なんで会えないのぉ？
